auto_test/api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    # 登陆页面
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

    # 产品页面
    path('product_manage/', views.product_manage, name='product_manage'),
    path('add_product/', views.add_product, name='add_product'),
    path('product_delete/', views.product_delete, name='product_delete'),
    path('update_product/', views.update_product, name='update_product'),

    # 接口页面
    path('apis_manage/', views.apis_manage, name='apis_manage'),
    path('add_apis/', views.add_apis, name='add_apis'),
    path('apis_update/', views.apis_update, name='apis_update'),
    path('apis_delete/', views.apis_delete, name='apis_delete'),

    # 流程页面
    path('api_test_manage/', views.api_test_manage, name='api_test_manage'),
    path('add_api_test/', views.add_api_test, name='add_api_test'),
    path('api_delete/', views.api_delete, name='api_delete'),
    path('api_update/', views.api_update, name='api_update'),

    # 流程接口步骤页面
    path('api_step_manage/', views.api_step_manage, name='api_step_manage'),
    path('add_api_step/', views.add_api_step, name='add_api_step'),
    path('api_step_delete/', views.api_step_delete, name='api_step_delete'),
    path('api_step_update/', views.api_step_update, name='api_step_update'),

    # Bug页面
    path('bug_manage/', views.bug_manage, name='bug_manage'),
    path('add_bug/', views.add_bug, name='add_bug'),
    path('bug_delete/', views.bug_delete, name='bug_delete'),
    path('bug_update/', views.bug_update, name='bug_update'),

    # 系统设置页面
    path('set_manage/', views.set_manage, name='set_manage'),
    path('add_set/', views.add_set, name='add_set'),
    path('set_user_manage/', views.set_user_manage, name='set_user_manage'),

    # app用例页面
    path('app_test_manage/', views.app_test_manage, name='app_test_manage'),
    path('add_app_test/', views.add_app_test, name='add_app_test'),
    path('app_delete/', views.app_delete, name='app_delete'),
    path('app_update/', views.app_update, name='app_update'),

    # app用例步骤页面
    path('app_step_manage/', views.app_step_manage, name='app_step_manage'),
    path('add_app_step/', views.add_app_step, name='add_app_step'),
    path('app_step_delete/', views.app_step_delete, name='app_step_delete'),
    path('app_step_update/', views.app_step_update, name='app_step_update'),

    # web用例页面
    path('web_test_manage/', views.web_test_manage, name='web_test_manage'),
    path('add_web_test/', views.add_web_test, name='add_web_test'),
    path('web_delete/', views.web_delete, name='web_delete'),
    path('web_update/', views.web_update, name='web_update'),

    # web用例步骤页面
    path('web_step_manage/', views.web_step_manage, name='web_step_manage'),
    path('add_web_step/', views.add_web_step, name='add_web_step'),
    path('web_step_delete/', views.web_step_delete, name='web_step_delete'),
    path('web_step_update/', views.web_step_update, name='web_step_update'),

    # 测试报告页面
    path('apis_report/', views.apis_report, name='apis_report'),
    path('api_test_report/', views.api_test_report, name='api_test_report'),
    path('web_report/', views.web_report, name='web_report'),
    path('app_report/', views.app_report, name='app_report'),

    # celery定时任务页面
    path('celery_manage/', views.celery_manage, name='celery_manage'),
    path('celery_delete/', views.celery_delete, name='celery_delete'),

    # 搜索功能页面
    path('pro_search/', views.pro_search, name='pro_search'),
    path('apis_search/', views.apis_search, name='apis_search'),
    path('api_test_search/', views.api_test_search, name='api_test_search'),
    path('web_search/', views.web_search, name='web_search'),
    path('app_search/', views.app_search, name='app_search'),
    path('bug_search/', views.bug_search, name='bug_search'),

    # Jenkins持续集成、Locust性能测试页面
    path('jenkins_page/', views.jenkins_page, name='jenkins_page'),
    path('locust_page/', views.locust_page, name='locust_page'),
    path('celery_page/', views.celery_page, name='celery_page'),

    # Celery test
    path('do/', views.do, name='do'),
]

auto_test/auto_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('at/',include(('api.urls','at'),namespace='at')),
]

auto_test/templates/add_apis.html
{% extends 'home.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/add_apis.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
        <div id="test_content_apis">
            <h3 id="add_test_name">添加接口用例</h3>
            <div id="title_apis">
                <form id="product_input" method="post" action="{% url 'at:add_apis' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label id='product_name_distance' for="p_name_input">产品：</label>
                        <br><br>
                        <select class="form-control" name="dropdown">
                            {% for pro_name in pro_names %}
                                <option  value="{{ pro_name.pk }}">
                                    {{ pro_name.p_product_name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_des_input">接口用例名称：</label>
                        <br><br>
                        <input name="api_name" type="text" class="form-control" id="p_des_input"
                               placeholder="输入接口用例名称">
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">Url地址：</label>
                        <br><br>
                        <input name="api_url" type="text" class="form-control" id="p_er_input" placeholder="输入Url地址">
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">请求参数和值：</label>
                        <br><br>
                        <input name="api_param_value" type="text" class="form-control" id="p_er_input" placeholder="输入请求参数和值">
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">请求方法：</label>
                        <br><br>
                        <input type="checkbox" value="get" name="method_check" >get
                        &nbsp
                        <input type="checkbox" value="post" name="method_check" >post
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">预期结果：</label>
                        <br><br>
                        <input name="api_result" type="text" class="form-control" placeholder="输入预期结果">
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">测试结果：</label>
                        <br><br>
                        <input name="api_status" value="1" type="checkbox" >True
                        &nbsp
                        <input name="api_status" value="0" type="checkbox" >False
                    </div>
                    <button type="submit" class="btn">保存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

auto_test/templates/add_app_test.html
{% extends 'home.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/add_apis.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
        <div id="test_content_apis">
            <h3 id="add_test_name">添加App用例</h3>
            <div id="title_apis">
                <form id="product_input" method="post" action="{% url 'at:add_app_test' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label id='product_name_distance' for="p_name_input">产品：</label>
                        <br><br>
                        <select class="form-control" name="dropdown">
                            {% for pro_name in pro_names %}
                                <option  value="{{ pro_name.pk }}">
                                    {{ pro_name.p_product_name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_des_input">App用例名称：</label>
                        <br><br>
                        <input name="app_t_name" type="text" class="form-control" id="p_des_input"
                               placeholder="输入App用例名称">
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">App用例描述：</label>
                        <br><br>
                        <input name="app_t_desc" type="text" class="form-control" id="p_er_input" placeholder="输入App用例描述">
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">测试负责人：</label>
                        <br><br>
                        <input name="app_ter" type="text" class="form-control" id="p_er_input" placeholder="输入测试负责人">
                    </div>
                    <div class="form-group">
                        <label id='product_name_distance' for="p_er_input">测试结果：</label>
                        <br><br>
                        <input name="app_t_res" value="1" type="checkbox" >True
                        &nbsp
                        <input name="app_t_res" value="0" type="checkbox" >False
                    </div>
                    <button type="submit" class="btn">保存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

auto_test/templates/app_t_search.html
{% extends 'home.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/app_test_manage.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
        <div id="test_content">
            <div id="test_list">
                <a id="title_distance" href={% url 'at:apis_manage' %}>单一接口用例</a>
                <a id="title_distance" href={% url 'at:api_test_manage' %}>流程接口用例</a>
                <a id="title_distance" href={% url 'at:web_test_manage' %}>Web测试用例</a>
                <a id="title_distance" href={% url 'at:app_test_manage' %}>App测试用例</a>
            </div>
            <h3 id="add_test_name">App用例列表</h3>
            <a id="add_test" href={% url 'at:add_app_test' %}>＋添加App用例</a>
            <div id="test_search">
                <form method="get" action="{% url 'at:app_search' %}">
                    {% csrf_token %}
                    <input type="search" name="app_t_name" placeholder="输入App用例名称">&nbsp;
                    <button id="search_b" type="submit" class="btn btn-default">搜索</button>
                </form>
            </div>

            <form id="" method="post" action="{% url 'at:app_test_manage' %}">
                {% csrf_token %}
                <table class="table-striped" id="table_list">
                    <thead>
                    <tr id="tr_title">
                        <th id="table_title_length">ID</th>
                        <th id="table_title_length4">产品名称</th>
                        <th id="table_title_length4">App用例名称</th>
                        <th id="table_title_length4">App用例描述</th>
                        <th id="table_title_length4">测试负责人</th>
                        <th id="table_title_length4">测试结果</th>
                        <th id="table_title_length3">时间</th>
                        <th id="table_title_length">查看</th>
                        <th id="table_title_length">编辑</th>
                        <th id="table_title_length">删除</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for app_t in app_tests %}
                        <tr id="tr_d">
                            <td>{{ app_t.id }}</td>
                            <td>{{ app_t.app_t_pro.p_product_name }}</td>
                            <td>{{ app_t.app_t_name }}</td>
                            <td>{{ app_t.app_t_desc }}</td>
                            <td>{{ app_t.app_ter }}</td>
                            <td>{% if app_t.app_t_res == 0 %}
                                <a style="color: red;text-decoration: none">{{ app_t.app_t_res }}</a>
                            {% elif app_t.app_t_res == 1 %}
                                <a style="color: green;text-decoration: none">{{ app_t.app_t_res }}</a>
                            {% endif %}
                            </td>
                            <td>{{ app_t.create_time }}</td>
                            <td><a href="{% url "at:app_step_manage" %}?app_t.id={{ app_t.id }}"
                                   class="glyphicon glyphicon-ok-sign" id="check_f"></a></td>
                            <td>编辑</td>
                            <td>删除</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
          
        </div>
    </div>

{% endblock %}

auto_test/templates/app_test_manage.html
{% extends 'home.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/app_test_manage.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
        <div id="test_content">
            <div id="test_list">
                <a id="title_distance" href={% url 'at:apis_manage' %}>单一接口用例</a>
                <a id="title_distance" href={% url 'at:api_test_manage' %}>流程接口用例</a>
                <a id="title_distance" href={% url 'at:web_test_manage' %}>Web测试用例</a>
                <a id="title_distance" href={% url 'at:app_test_manage' %}>App测试用例</a>
            </div>
            <h3 id="add_test_name">App用例列表</h3>
            <a id="add_test" href={% url 'at:add_app_test' %}>＋添加App用例</a>
            <div id="test_search">
                <form method="get" action="{% url 'at:app_search' %}">
                    {% csrf_token %}
                    <input type="search" name="app_t_name" placeholder="输入App用例名称">&nbsp;
                    <button id="search_b" type="submit" class="btn btn-default">搜索</button>
                </form>
            </div>

            <form id="" method="post" action="{% url 'at:app_test_manage' %}">
                {% csrf_token %}
                <table class="table-striped" id="table_list">
                    <thead>
                    <tr id="tr_title">
                        <th id="table_title_length">ID</th>
                        <th id="table_title_length4">产品名称</th>
                        <th id="table_title_length4">App用例名称</th>
                        <th id="table_title_length4">App用例描述</th>
                        <th id="table_title_length4">测试负责人</th>
                        <th id="table_title_length4">测试结果</th>
                        <th id="table_title_length3">时间</th>
                        <th id="table_title_length">查看</th>
                        <th id="table_title_length">编辑</th>
                        <th id="table_title_length">删除</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for app_t in app_tests %}
                        <tr id="tr_d">
                            <td>{{ app_t.id }}</td>
                            <td>{{ app_t.app_t_pro.p_product_name }}</td>
                            <td>{{ app_t.app_t_name }}</td>
                            <td>{{ app_t.app_t_desc }}</td>
                            <td>{{ app_t.app_ter }}</td>
                            <td>{% if app_t.app_t_res == 0 %}
                                <a style="color: red;text-decoration: none">{{ app_t.app_t_res }}</a>
                            {% elif app_t.app_t_res == 1 %}
                                <a style="color: green;text-decoration: none">{{ app_t.app_t_res }}</a>
                            {% endif %}
                            </td>
                            <td>{{ app_t.create_time }}</td>
                            <td><a href="{% url "at:app_step_manage" %}?app_t.id={{ app_t.id }}"
                                   class="glyphicon glyphicon-ok-sign" id="check_f"></a></td>
                            <td><a style="color:cadetblue "
                                   href="{% url 'at:app_update' %}?app_t.id={{ app_t.id }}">编辑</a></td>
                            <td><a style="color: #cc0000" href="javascript:"
                                   onclick="confirm_delete(this,{{ app_t.id }})">删除</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
            <!--分页-->
            <div id="pager">
                <nav aria-label="Page navigation">
                    <ul class="pagination">

                        {% if app_tests.has_previous %}
                            <li>
                                <a href="?page={{ app_tests.previous_page_number }}&app_t_name={{ search_name }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>

                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page_index in app_tests.paginator.page_range %}
                            {% ifequal page_index  app_tests.number %}
                                <li class="active">
                                    <a style="background: cadetblue"
                                       href="?page={{ page_index }}&app_t_name={{ search_name }}">{{ page_index }}</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="?page={{ page_index }}&app_t_name={{ search_name }}">{{ page_index }}</a>
                                </li>
                            {% endifequal %}

                        {% endfor %}

                        {% if app_tests.has_next %}
                            <li>
                                <a href="?page={{ app_tests.next_page_number }}&app_t_name={{ search_name }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}

                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        //删除文章函数
        function confirm_delete(the, app_id) {
            {#var pro_name = $(the).parents("tr").children("td").eq(1).text();#}
            //调用layer函数
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["190", "110px"],

                //弹窗标题
                title: "删除",
                content: "确认删除？",
                //点击确定后调用的回调函数
                btn: ['确定', '取消'], yes: function () {
                    $.ajax({
                        url: '{% url "at:app_delete" %}',
                        type: "GET",
                        data: {"app_id": app_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("已删除");
                            } else {
                                layer.msg("删除失败");
                            }
                        }
                    })
                },
            })
        }
    </script>

{% endblock %}

auto_test/templates/celery_page.html
{% extends 'home.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/jenkins_page.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
        <div id="product_content">
            <h2 id="title_name">条件1：启动Redis cmd命令 redis-server redis.windows.conf</h2>
            <h2 id="title_link">条件2：启动Celery worker 处理任务 python manage.py celery worker -l info</h2>
            <h2 id="title_link1">条件3：启动Celery beat 负责把任务分发给worker python manage.py celery beat -l info</h2>

        </div>
    </div>


{% endblock %}

auto_test/templates/product_manage.html
{% extends 'home.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/product_manage.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
        <div id="product_content">
            <h3 id="add_product_name">产品列表</h3>
            <a id="add_product" href={% url 'at:add_product' %}>＋添加产品</a>
            <div id="search_p">
                <form method="get" action="{% url 'at:pro_search' %}">
                    {% csrf_token %}
                    <input style="" type="search" name="p_product_name" placeholder="输入产品名称">
                    &nbsp;<button type="submit" id="search_b" class="btn btn-default">搜索</button>
                </form>
            </div>

            <form id="" method="post" action="{% url 'at:product_manage' %}">
                {% csrf_token %}
                <table class="table-striped" id="table_list">
                    <thead>
                    <tr id="tr_title">
                        <th id="table_title_length">ID</th>
                        <th id="table_title_length2">产品名称</th>
                        <th id="table_title_length2">产品描述</th>
                        <th id="table_title_length3">产品负责人</th>
                        <th id="table_title_length3">时间</th>
                        <th id="table_title_length">编辑</th>
                        <th id="table_title_length">删除</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for product in products %}
                        <tr id="tr_d">
                            <td>{{ product.id }}</td>
                            <td>{{ product.p_product_name }}</td>
                            <td>{{ product.p_product_desc }}</td>
                            <td>{{ product.p_product_er }}</td>
                            <td>{{ product.create_time }}</td>
                            <td>
                                <a style="color: cadetblue"
                                   href="{% url 'at:update_product' %}?product.id={{ product.id }}">编辑</a>
                            </td>
                            <td><a style="color: #cc0000"
                                   href="javascript:" onclick="confirm_delete(this,{{ product.id }})">删除</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>

            <!--分页-->
            <div id="pager">
                <nav aria-label="Page navigation">
                    <ul class="pagination">

                        {% if products.has_previous %}
                            <li>
                                <a href="{% url 'at:pro_search' %}?&p_product_name={{ search_name }}&page={{ products.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>

                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page_index in products.paginator.page_range %}
                            {% ifequal page_index  products.number %}
                                <li class="active">
                                    <a style="background: cadetblue"
                                       href="?p_product_name={{ search_name }}&page={{ page_index }}">{{ page_index }}</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="?p_product_name={{ search_name }}&page={{ page_index }}">{{ page_index }}</a>
                                </li>
                            {% endifequal %}

                        {% endfor %}

                        {% if products.has_next %}
                            <li>
                                <a href="{% url 'at:pro_search' %}?p_product_name={{ search_name }}&page={{ products.next_page_number }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        //删除文章函数
        function confirm_delete(the, product_id) {
            {#var pro_name = $(the).parents("tr").children("td").eq(1).text();#}
            //调用layer函数
            layer.open({
                type: 1,
                skin: "layui-layer-rim",
                area: ["190", "110px"],

                //弹窗标题
                title: "删除",
                content: "确认删除？",
                //点击确定后调用的回调函数
                btn: ['确定', '取消'], yes: function () {
                    $.ajax({
                        url: '{% url "at:product_delete" %}',
                        type: "GET",
                        data: {"product_id": product_id},
                        success: function (e) {
                            if (e == "1") {
                                parent.location.reload();
                                layer.msg("已删除");
                            } else {
                                layer.msg("删除失败");
                            }
                        }
                    })
                },
            })
        }

    </script>


{% endblock %}

auto_test/templates/set_user_manage.html
{% extends 'home.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/set_user_manage.css' %}">
{% endblock %}

{% block content %}
    <div class="content">
        <div id="test_content">
            <div id="test_list">
                <a id="title_distance" href={% url 'at:set_manage' %}>公共设置</a>
                <a id="title_distance" href={% url 'at:set_user_manage' %}>用户管理</a>
            </div>
            <h3 id="add_test_name">用户管理列表</h3>
{#            <a id="add_test" href={% url 'at:add_apis' %}>＋添加公共变量</a>#}
{#            <a id="test_search">搜索</a>#}

            <form id="" method="post" action="{% url 'at:set_user_manage' %}">
                {% csrf_token %}
                <table class="table-striped" id="table_list">
                    <thead>
                    <tr id="tr_title">
                        <th id="table_title_length">ID</th>
                        <th id="table_title_length2">用户名称</th>
                        <th id="table_title_length2">密码</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in at_user %}
                        <tr id="tr_d">
                            <td>{{ user.id }}</td>
                            <td>{{ user.u_username }}</td>
                            <td>{{ user.u_password }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
        <!--分页-->
            <div id="pager">
                <nav aria-label="Page navigation">
                    <ul class="pagination">

                        {% if at_user.has_previous %}
                            <li>
                                <a href="?page={{ at_user.previous_page_number }}&search_name={{ search_name }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>

                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for page_index in at_user.paginator.page_range %}
                            {% ifequal page_index  at_user.number %}
                                <li class="active">
                                    <a style="background: cadetblue"
                                       href="?page={{ page_index }}">{{ page_index }}</a>
                                </li>
                            {% else %}
                                <li>
                                    <a href="?page={{ page_index }}">{{ page_index }}</a>
                                </li>
                            {% endifequal %}

                        {% endfor %}

                        {% if at_user.has_next %}
                            <li>
                                <a href="?page={{ at_user.next_page_number }}&search_name={{ search_name }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}